services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./data:/usr/src/app/data
    environment:
      NODE_ENV: development
